import { useNavigate } from "react-router-dom";
import Button from "../../components/buttons/Button";
import Header from "../../components/header/Header";

import './Footer.css';

const TermsConditions = () => {
    const navigate = useNavigate()
    return (
        <><Header />
            <div className="content container">
                <h2>Privacy Policy</h2>
                <p>We respect the privacy of those who visit our website. In accordance with this, we have created this policy in order to demonstrate our privacy commitment to our users.</p>

                <p>This website <a href="http://www.upeducators.com">www.upeducators.com</a> is owned and operated by upEducators / upEducators Masterclass. All rights of this website are reserved with upEducators / upEducators Masterclass. No part or content of this website may be reproduced, replicated, distributed, or transmitted in any form whatsoever or through any means, which includes printing, recording or other electronic methods or any other methods, as the case may be, without prior written permission from the administrator of this website. Users may download material from the website only for their own personal, non-commercial use. For commercial permission requests, please contact the Web administrator.</p>

                <p>upEducators / upEducators Masterclass reserves the right to make changes to any information contained on the website at any time whatsoever, and without notice or limitation of any kind, including, but not limited to, information relating to countries, courses, universities, scholarships, fees, and other related services.</p>

                <h2>Privacy Commitment</h2>
                <p>upEducators / upEducators Masterclass understand and respect the privacy concerns of visitors to our website. upEducators / upEducators Masterclass is committed to respecting your online privacy and recognizes your need for appropriate protection and management of any personally identifiable information or private communication. We take care that the content posted on this website is appropriate for viewing and/or use. This Privacy Policy outlines the way in which upEducators / upEducators Masterclass gathers and uses information relating to you.</p>

                <h2>What this Privacy Policy Covers?</h2>
                <p>This Privacy Policy covers our treatment of personally identifiable information that we collect when you are on our site and when you use our services. This policy also covers our treatment of any personally identifiable information that third parties share with us. This policy does not apply to the practices of organizations that we do not own or control or to people that we do not employ or manage.</p>

                <h2>Information Collection and Use</h2>
                <h3>Personally Identifiable Information upEducators / upEducators Masterclass Collects</h3>
                <p>We collect no personal information about you when you visit our website unless you choose to provide this information to us. If you do nothing during your visit but browse through the website, read pages, or download information, we will gather and store certain information about your visit automatically. This information does not identify you personally. Rather, information is kept in the aggregate. We automatically collect and store only the information about your visit. We use the information we collect to understand the traffic to our site and to help us make our site more useful to visitors like you.</p>
                <p>We also automatically receive and record information on our server logs from your browser including your IP address, cookie information, and the page you requested. This information is not linked to your account and will not be used to identify you.</p>
                <p>We collect personally identifiable information when you register on our website, when you use our services, and when you visit our pages. We collect personally identifiable information (via online or offline registration forms), such as name, contact details, e-mail address, postal address, telephone/mobile number, gender, date of birth, occupation, industry, personal interests, etc., when you provide it to us or when you register with us. Once you register with us and sign in to our services, you are not anonymous to us. We may also receive information about you from other sources/third parties and add it to the information you have provided to us.</p>
                <p>We use this information for three general purposes: to customize the content you see, to fulfill your requests for certain services, and to contact you about services:</p>
                <ul>
                    <li>We may combine personal information collected from you with other information from data available with us to provide a better overall experience, including customizing content for you in both forms – online (or electronic) as well as offline.</li>
                    <li>We do not monitor your use of the Internet; neither do we use cookie technology or any other technology to monitor your use of <a href="http://www.upeducators.com">www.upeducators.com</a>. We may receive and collect certain anonymous information in standard usage logs through our Web server. This information may include the IP address assigned to the computer you use while accessing <a href="http://www.upeducators.com">www.upeducators.com</a>.</li>
                    <li>We may use personal information to provide the services you’ve requested, including services that display customized content and advertising.</li>
                    <li>We may use this information for billing purposes and to fill your orders. If we have trouble processing an order, we will use this information to contact you.</li>
                    <li>We may also use personal information for auditing, research, and analysis to operate and improve upEducators / upEducators Masterclass’ products and services.</li>
                </ul>

                <h2>Information Sharing and Disclosure</h2>
                <p>We will send personally identifiable information about you to other companies or people when:</p>
                <ul>
                    <li>We have your consent to share the information;</li>
                    <li>We respond to subpoenas, court orders, or legal process; or</li>
                    <li>We find that your actions on our web sites violate the Terms of Service.</li>
                </ul>
                <p>We will not sell or rent your personal identifiable information to anyone/any third party/or non-affiliated companies for commercial gains. However, we may, at times, mail promotional material that we believe will be of relevance to you on behalf of third parties and for which we may receive a consideration from the party in question. However, even in such situations, all data will remain solely in the possession of upEducators / upEducators Masterclass and will not be shared with any third party.</p>
                <p>We may present information to advertisers who wish to advertise on our website. When we present information to our advertisers it is to help them understand our audience and confirm the value of advertising on our website. Such information is in the form of aggregated statistics on traffic to various pages within our site.</p>
                <p>We are the sole owners of your information collected by us at several different points on our Website. However, we may share information with third parties in limited circumstances, including when complying with legal process, for authorized law enforcement investigations, preventing fraud or imminent harm, and ensuring the security of our network and services.</p>
                <p>We provide the information to our trusted partners who work on behalf of or with upEducators / upEducators Masterclass under confidentiality agreements. These companies may use your personal information to help upEducators / upEducators Masterclass communicate with you about offers from upEducators / upEducators Masterclass and our marketing partners. However, these companies do not have any independent right to share this information.</p>
                <p>We respond to subpoenas, court orders, or legal process, or to establish or exercise our legal rights or defend against legal claims. We also may disclose personal information to third parties if we have reason to believe that disclosing such information is necessary to conduct investigations of possible breaches of law, to cooperate in any legal investigation, or to identify, contact, or bring legal action against someone who may be violating the terms of use of our site.</p>
                <p>We believe it is necessary to share information in order to investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of upEducators / upEducators Masterclass’ terms of use, or as otherwise required by law.</p>
                <p>We transfer information about you if upEducators / upEducators Masterclass is acquired by or merged with another company. In this event, upEducators / upEducators Masterclass will notify you before information about you is transferred and becomes subject to a different privacy policy.</p>
                <p>upEducators / upEducators Masterclass displays targeted advertisements based on personal information. Advertisers (including ad serving companies) may assume that people who interact with, view, or click on targeted ads meet the targeting criteria.</p>
                <p>upEducators / upEducators Masterclass does not provide any personal information to the advertiser when you interact with or view a targeted ad. However, by interacting with or viewing an ad you are consenting to the possibility that the advertiser will make the assumption that you meet the targeting criteria used to display the ad.</p>
                <p>upEducators / upEducators Masterclass is not responsible for the information you volunteer about yourself in the course of discussions in our forums, chat rooms, or other forms of publicly accessible interaction or information that you choose to make public in your member profile. As a member, you can view, correct or change your publicly available information at any time via your member profile page.</p>

                <h2>Information Security</h2>
                <p>We take appropriate security measures to protect against unauthorized access to or unauthorized alteration, disclosure or destruction of data.</p>
                <p>The information you provide to us will be held on upEducators / upEducators Masterclass’ own servers or on third-party servers contracted by upEducators / upEducators Masterclass. The database is stored on servers secured behind a firewall; access to the servers is password-protected and is strictly limited. However, as effective as our security measures are, no security system is impenetrable. We cannot guarantee the security of our database, virus attacks, system errors/bugs, nor can we guarantee that information you supply will not be intercepted while being transmitted to us over the Internet.</p>
                <p>We use reasonable precautions to keep the personal information you disclose to our website, secure and to only release this information to third parties we believe share our commitment to privacy. However, we are not responsible for any breach of security or for the actions of these parties.</p>
                <p>Although we will endeavor to meet the requirements of the Internet Security policy envisaged under this section, we cannot accept any responsibility for any loss, disruption, or damage to your data or your computer system that may occur whilst using material derived from this website. As best practice, we also strongly recommend that you regularly run an antivirus program on all material downloaded from the Internet.</p>

                <h2>Online Ad Serving</h2>
                <p>upEducators may use advertising services of third parties to serve advertisements when you visit our sites. These companies may use information (not including your name, address, e-mail address, telephone number, or any other information you’ve provided to us) about your visits to our and other websites in order to provide advertisements about goods and services of interest to you. You agree and understand that upEducators neither owns nor operates/controls any information or services provided on such third-party websites. You further agree and understand that such links do not constitute an endorsement by upEducators of any such websites and are provided only as a convenience. upEducators is not responsible for the content or links displayed on such websites.</p>
                <p>Several companies may provide email deployment services for our email messages. The personally identifiable information, such as e-mail addresses, we provide to these vendors for the purposes of email deployment is only used by them for that purpose and not for any other business activity. We do not give any personally identifiable information to them as part of this relationship. Use of their tracking technology is subject to their own privacy policies.</p>

                <h2>Links to Other Websites</h2>
                <p>Our website has links to partners and other sites. When you link to another site, you are no longer on our site and are subject to the privacy policy of the new site. Other websites may collect and treat information collected differently, so we encourage you to carefully read and review the privacy policy for each website you visit. We will not be responsible for any information that you may provide to such websites accessible through our website.</p>

                <h2>Restriction of Liability</h2>
                <p>upEducators makes no claims, promises, or guarantees about the accuracy, completeness, or adequacy of the contents of this website and expressly disclaims liability for errors and omissions in the contents of this website.</p>
                <p>No warranty of any kind, implied, expressed, or statutory, including but not limited to the warranties of non-infringement of third-party rights, title, merchantability, fitness for a particular purpose, and freedom from computer virus, is given with respect to the contents of this website or its hyperlinks to other Internet resources.</p>
                <p>Reference in this website to any specific commercial products, processes, or services, or the use of any trade, firm, or corporation name is for the information and convenience of the public and does not constitute endorsement, recommendation, or favoring by upEducators.</p>
                <p>Advertisements are subject to the Privacy Policy of the advertising site.</p>

                <h2>Changes to this Privacy Policy</h2>
                <p>The privacy policy is subject to modification from time to time. upEducators reserves the right to update, change, or modify this policy at any time without any prior notification. The policy shall come into effect from the date of such update, change, or modification. If we decide to change our privacy policy, we will post those changes here so that you will always know what information we gather, how we might use that information, and whether we will disclose it to anyone. Any significant changes to our privacy policy will be announced on our page. By using this website, you consent to the terms of this Privacy Policy and signify your assent to all of the terms of this Privacy Policy and our Terms of Use. If you do not agree with the changes in our policy or with any term of this Privacy Policy you can simply exit from our website, discontinue to visit our website and not submit any personally identifiable information.</p>

                <h2>General Terms & Conditions</h2>
                <p>The information displayed on this site is provided on a ‘best efforts’ and ‘as is’ basis without any warranties of any kind, including, but not limited to any implied warranties of merchantability or fitness for any particular purpose. The users of <a href="http://www.upeducators.com">www.upeducators.com</a> claim the entire responsibility for the selection and use of the service(s) and neither upEducators nor any of its information providers, licensors, employees, partners, or agents shall have any liability for any errors, malfunctions, defects, or loss of data, resulting from the use or inability to use the service. In no event shall the liability of upEducators, if any, exceed the amount paid, if any, by the user. While utmost care is taken to provide correct and up-to-date information, upEducators does not warrant the accuracy, completeness, and timely availability of the information provided on the site and accepts no responsibility or liability for any error or omission in any information provided on the site nor does the site claim to be comprehensive in its coverage of examinations (either competitive or otherwise in nature) and/or of the various educational programs conducted in India.</p>
                <p>upEducators expressly disclaims any warranties whether express or implied about the suitability, reliability, availability, timeliness, correctness, completeness, quality, continuity, performance, or fitness of products or services contained/displayed within this website for any purpose.</p>

                <h2>User Communications</h2>
                <p>Accepting these T&C implies your express consent to be contacted by us, our agents, representatives, affiliates, or anyone calling on our behalf at any contact number, or physical or electronic address provided by you while registering your Account/filling up the form. You further agree to us contacting you in any manner, including without limitation, SMS messages (including text messages), calls using pre-recorded messages or artificial voice, calls and messages delivered using auto telephone dialing systems or automatic texting systems, and notifications sent via the Services. Automated messages may be played when the telephone is answered whether by you or someone else. If an agent or representative calls, he or she may also leave a message on your answering machine, voice mail, or send one via SMS.</p>
                <p>You certify, warrant, and represent that the telephone numbers and/or email addresses and any other information that you have provided (at the time of registering on the Website or thereafter or for creating an Account) to us are your own and not someone else’s and are true, accurate, current, and complete. You represent that you are permitted to receive calls and SMS at each of the telephone/mobile numbers you have provided to us and emails at each of the email addresses you have provided us. You agree to notify us whenever you stop using a telephone/mobile number(s) and/or email address(es).</p>
                <Button title='Back' onClick={()=> navigate('/')}  />
            </div>
            </>
    )
};
export default TermsConditions;